### ISSUE TITLE
alarm names should be unique

### ISSUE THREAD

**Issue by SevereOverfl0w** [cloudposse/terraform-aws-rds-cloudwatch-sns-alarms#5]
terraform doesn't complain about the conflict, but the alarms will constantly have their dimension overwritten with every deploy if the names aren't unique.

**Comment by osterman** [comment]
100% agree. We should be using the `terraform-null-label` module here.

**Comment by osterman** [comment]
Any chance you have time to submit a PR for this @SevereOverfl0w ?

**Comment by SevereOverfl0w** [comment]
Potentially, I'll drop a note here if I find the time and start working on it. It is a problem for us as we have multiple dbs, so I'll be inclined to fix it at some point.

**Comment by rebelthor** [comment]
Until a better solution is implemented, I've added unicity based on instance ID via PR #10

**Comment by RoryKiefer** [comment]
.... just add the rds_instance_id in front of the alarm name with a dash

in local testing, it fixes the issue:
`alarm_name:                            "swap_usage_too_high" => "clutchwh-swap_usage_too_high" (forces new resource)`

**Comment by SnufflesC137** [comment]
This can be easily fixed by including the instance id before the alarm name, example:

```  alarm_name          = "${var.db_instance_id}_cpu_utilization_too_high"```
